### ISSUE TITLE
Discuss possible logging options

### ISSUE THREAD

**Issue by mellinma** [OregonDigital/oregondigital#1051] opened 2016-08-18 22:39 UTC
Discuss possible logging options for edits to items (logfile, DB, Papertrail, etc.) - a logfile would be pretty quick to add, with email and pid - database for quick filtering

From 8/18/16 meeting at UO

**Comment by duncanbarth** [comment] 2017-01-05 23:36
duplicate of 1049

**Closed by duncanbarth** 2017-01-05 23:36 UTC
Labels: backlog, priority
