### ISSUE TITLE
OSU is ... not English?

### ISSUE THREAD

**Issue by jechols** [OregonDigital/oregondigital#745] opened 2015-01-16 01:45 UTC
"Universidade do Estado do Oregon"

**Comment by boockm** [comment] 2015-01-16 16:42
We've noticed this and Brian was preparing a ticket. Occasionally it appears as other languages, such as Arabic!

**Comment by terrellt** [comment] 2015-01-16 16:42
Yeah - it seems like the fetch mechanism doesn't always get all the labels from dbpedia.

**Comment by tvc15brian** [comment] 2015-01-16 16:48
Eu sou como o português.

**Comment by terrellt** [comment] 2015-01-16 17:11
If #19 is merged we should be able to take care of this.

**Comment by jechols** [comment] 2015-01-16 17:44
That PR seems like it will deal with the symptom, but not the cause.  Is this a problem with dbpedia that we can't control, then?  Or is this something in our fetch that could potentially blow up in other ways?

**Comment by jechols** [comment] 2015-01-16 17:48
FYI, merged it

**Comment by terrellt** [comment] 2015-01-16 18:07
> That PR seems like it will deal with the symptom, but not the cause. Is this a problem with dbpedia that we can't control, then? Or is this something in our fetch that could potentially blow up in other ways?

*Shrug* I've only seen it with dbpedia, but there are other problems with the fetch mechanism which are likely caused by the constant re-fetches (OSU's resource often gets polluted with thousands of triples for some reason.)

**Comment by terrellt** [comment] 2015-01-20 19:10
There are fetch jobs running to fix this, but some ingests are being prioritized ahead of them.

**Comment by jechols** [comment] 2015-01-22 20:51
Argh!  OSU and UO both now have unexpected labels, but only sometimes:

![osu-labels](https://cloud.githubusercontent.com/assets/2157974/5864246/4dc029c4-a235-11e4-9f8e-7f25ed86c6db.png)

**Comment by terrellt** [comment] 2015-01-22 21:25
Yeah, I don't know if it's fetching, RDF::Graph, AF::RDF::Resource, or the mongo store that hates me.

**Comment by mickeroo** [comment] 2015-01-26 21:45
Since this is related to the "fetched labels disappearing" roadblock we discussed at the Hydra meeting on 1/23 I'm adding the notes:

- Possible Reasons: 
  - truncates data from the response
  - or finds nothing and persists nothing 
- **Possible Solution: we could have it not fetch again if there’s already a label**

We get the wrong language because it picks english first and if mongo is dropping them then it’ll pick the next one in the list.  Is the issue with Mongo RDF gem?
However, if Mongo is dropping labels it would be a lot more work - possibly involving Marmotta:
- it would handle the fetching and caching 
- would bypass the fetch code entirely 
- issue might be with how well Marmotta scales?
- may have to use resource API and not the SPARQL endpoint
- not sure how fast it really is at scale

Impact on the upgrade? work should transfer with the upgrade.

This is also related to #744

**Comment by terrellt** [comment] 2015-01-28 00:36
I'm running a fetch on all the CVs with the new setup - we'll see if it helps.

**Comment by terrellt** [comment] 2015-01-28 18:10
Did NOT help. Turns out the problem is with MongoDB indexes being too big.  #778 and #779 should help.

**Comment by terrellt** [comment] 2015-01-29 16:18
Labels are looking good!

**Closed** 2015-01-30 16:54 UTC
Labels: blocker
