### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jcoyne** [OregonDigital/oregondigital#800] opened 2015-02-21 01:39 UTC
The license of this project is unclear. There should be a LICENSE.txt file or similar. See https://github.com/curationexperts/oargun/issues/2 :wink:

**Comment by terrellt** [comment] 2015-02-21 01:44
See #753

**Comment by wickr** [comment] 2015-02-27 00:33
Closed as duplicate of #721

**Closed by wickr** 2015-02-27 00:33 UTC
