### ISSUE TITLE
Ingest Art, Architecture and Design Digital Collection

### ISSUE THREAD

**Issue by wickr** [OregonDigital/oregondigital#855] opened 2015-06-29 18:00 UTC
http://oregondigital.org/cdm4/browse.php?CISOROOT=/art
3215 items

Julia and Sarah can help with mapping, Trey will generate bags

**Comment by jsimic** [comment] 2015-07-01 15:04
@sseymore : take a look at the mapping below

title: dct:title
creato: dce:creator
date: dct:date
period: dct:temporal #3213 total items 3194 designated centuries 13 items with actual style designations noted in spreadsheet correct by hand
catego: rdfs:type
materi: oregon:vra/material
proces: oregon:vra/material #some techniques some worktypes shove all into materials
dimens: oregon:vra/measurements
cultur: oregon:vra/culturalContext
reposi: marcrel:rps
region: dct:date
tribe: #SKIP one incorrect citation in field noted in spreadsheet correct by hand
descri: dct:description
access: dct:identifier
source: dct:source
subjec: dct:rights #Need new method
catalo: #SKIP
digita:
 method: set

**Comment by sseymore** [comment] 2015-07-01 15:39
Do we want to use Date Created since it's Creation Date and also some of those will have to be split into VRA Earliest and Latest Date it looks like. 

Also, could Object Type be Work Type?

For region, since there's only 2 items, I would move that to period: dct:temporal if that's ok to repeat that field or just clean up those 2 records. 

Rights- It looks like that will have to be cleaned up. There's a mixture of rights statements, rightsholder info, and use restriction statements. 

Add Contributing Institution, as well. 

I think that's it from what I can see. Let me know if anything is incorrect.

**Comment by jsimic** [comment] 2015-07-01 16:01
Re: Creation date, Sure, assuming they are actually creation dates. @wickr ??
Re: WorkType, We changed all workTypes to rdf:types and ditched the vra predicate.
Re: Region, I count three different entries in the CV and only 3 items, and at looks like they were just mistakenly put in region instead of date
Re: Rights, I count only two statements in the CV one that indicates rr-r and one more ambiguous, probably rr-f. @wickr ??

**Comment by boockm** [comment] 2015-07-01 16:12
Re: Creation date, Sure, assuming they are actually creation dates. @wickr ??

They are creation dates.

**Comment by terrellt** [comment] 2015-07-06 17:29
So I'm looking at `catego` and having a hard time mapping to URIs - AAT doesn't seem to have big general purpose things like "Painting." need URIs for
```ruby
Painting
Painting;
Photography
Drawing
Print
Photography;
Drawing; Diagram
Drawing;
Sculpture
Architecture
Sculpture;
Diagram
Documentary Photography;
Glasswork; painting
Glasswork; Multimedia works; Assemblages (sculpture)
Glasswork
Collage
Photomontage
Painting; Collage
Screen print
Collage;
Painting; Sculpture;
Painting; Photography;
Installation
Painting; Collage;
Painting; Stage Design
Painting; Assemblages (sculpture);
Painting; Drawing;
Combine painting
Assemblages (sculpture);
Painting; Diagram;
Painting; Screen print;
```

**Comment by terrellt** [comment] 2015-07-06 17:35
De-duplicated:
```
Painting
Photography
Drawing
Print
Diagram
Sculpture
Architecture
Documentary Photography
Glasswork
painting
Multimedia works
Assemblages (sculpture)
Collage
Photomontage
Screen print
Installation
Stage Design
Combine painting
```

**Comment by terrellt** [comment] 2015-07-06 17:41
Looking at Materi, not sure it's even possible to programmatically URI-ify these. De-duplication results in:

```
oil on canvas
oil on millboard
pastel
oil on paper glued to linen
oil on bedtick
watercolor on paper
watercolor
watercolor on ivory
oil on wood
oil on wood panel
paint on velvet
oil on board
oil on paper
pastel on paper
graphite, chalk and ink on paper
mounted on masonite
mounted on canvas
gouache
graphite
oil ink
ink
collage on paper
gold-colored metallic pigments
ink on paper
graphite on paper
charcoal
gouache on paper
collage
chalk on paper
charcoal on paper
pencil on paper
oil on velvet
pastel on canvas
oil on copper
oil on mahogany
wood
metal
oil on linen
oil on card
silver salts on paper
oil on composition board
oil on paperboard on wood panel
wash on wove paper lined with japanese tissue
brush
brown wash
oil on cardboard
bronze
oil on plaster
oil on burlap
oil on paperboard
pencil
oil on paper on canvas
albumen
over pencil
watercolor on composition board
over graphite on paper
over graphite
graphite on off-white woven paper
gum
oil chalk on canvas
oil
local glazes on paper
oil on panel
cradled
mounted on fiberboard
oil on metal
oil on canvas on cardboard
graphite pencil
crayon
marble
graphite on wove paper
conte
oil on slate board
needlework on silk
watercolor on heavy white paper
over graphite on heavy white paper
oil paint and gold leaf on canvas, leather and wood
acrylic on canvas
3 panels each
distemper on canvas
on canvas
egg tempera
tempera on canvas
oil egg tempera
oil egg tempera on canvas
mounted on aluminum panel
oil tempera on canvas
mounted on panel
tempera
oil glaze on canvas
mounted on wood panel
oil egg tempera on canvas on panel
polymer tempera on canvas
painted wood and glass
painted wood
glass
oil tempera on gesso panel
oil tempera on gesso board
methyl cellulose
oil on masonite
graphite on white wove paper
fused glass (transparent), dull ground, sand blown, black, painted and baked on pink gold.
stained glass and bottle fragments set in brass
fused glass, white in black (opaque), sand blown
fused glass, white in black (opaque), sandblown, black frosted wiith grey
opal glass, oil
liquitex on canvas
oil and canvas
mixed media
mixed media on board
paper and synthetic polymer on composition board
paper and synthetic polymer paint on composition board
mixed media and paint on panel
cut and pasted printed, colored and metallic papers, photostats, graphite, ink marker, gouache, watercolor, and ink on masonite
mixed media and acrylic on board
mixed media on paper
oil on canvas, 2 panels
enamel on masonite
enamel on canvas
watercolor and gouache over graphite
watercolor and gouache on paper
mixed media and oil on canvas
acrylic on canvas, 4 panels
watercolor, pencil, and carbon tracing on pieced paper
watercolor, pencil, carbon tracing, and collage on pieced paper
fiberglass
oil on academy board
oil and chalk on cardboard
oil and charcoal on canvas
oil and charcoal on composition board
oil pencil on paper
oil and charcoal on board
oil and enamel on paper, mounted on composition board
oil and enamel on fiberboard
pastel charcoal on paper
oil, enamel, charcoal on canvas
oil, enamel, and charcoal on canvas
oil, enamel and charcoal on canvas
oil and combined media on heavy paper
oil and charcoal on wood
oil on paper mounted on canvas
oil and collage on paper
charcoal and pastel on paper
oil and charcoal on panel
tempera and oil on canvas
tempera and oil on gesso panel
oil and tempera on gesso panel
colored pencil on paper
oil and enamel on cardboard
oil and enamel on canvas
watercolor and pencil on paper
tempera on cardboard
charcoal, oil and crayon on paper
tempera on paper
camera lens, photographic plate, clock springs, watch springs and steel wool on cardboard
oil on paper mounted on paper mounted on fiberboard and wood honeycomb panel
india ink and watercolor
watercolor, pen and black ink on paper
resin and fiberglass
watercolor over graphite pencil on paper
watercolor and graphite on textured wove paper
watercolor, pen and plack ink on buff paper
oil on canvas, wood, metal, light bulb
oil on canvas with mixed media
acrylic on canvas, 2 panels
paper, newspaper, fabric, cord, glass, pencil and watercolor on board
synthetic polymer on canvas
woodcut (4 blocks) on handmade paper
lithograph (2 stones) on handmade paper
sugarlift, aquatint, drypoint on handmade paper
tempera and wax
oil, dico, gouache, india ink on poster board
crayon on paper
oil and aqueous media on upsom board
oil on plywood
oil and tempera on masonite
acrylic on masonite
painted wood on composition board
acrylic and mixed media collage on paper
oil on cardboard mounted on masonite
oil on hardboard
collage, gouache, black ink, watercolor on paper
ink, gouache, watercolor on paper
glass and watercolor
encaustic and collage on canvas
encaustic on canvas
oil and objects on canvas
encaustic on wood
oil , encaustic, collage and objects on canvas
encaustic, collage and objects on canvas
oil an objects on canvas
oil and objects on canvas on wood
encaustic and objects on canvas
oil and encaustic on canvas
tempera, pen, ink and pencil on paper
tempera and ink wash on magazine page
tempera, collage and ink wash on magazine page
collage and ink wash on board
gouache, pen and ink on paperboard
gouache, pen and ink on paper
tempera, pencil and ink on paper
tempera, pen and ink on paper
oil on fiberboard
synthetic paint on canvas
oil and enamel on board
oil and paper on masonite
oil on cotton duck
paper on canvas
oil and collage on canvas
tempera on panel
magna and oil
magna on canvas
tempera on gesso on composition board
casein tempera on hardboard
egg tempera on composition board
casein on paper
tempera on hardboard
gouache and casin on paper
oil on canvas mounted on panel
casein and ink
oil and magna on canvas
oil and magna
oil and synthetic polymer on canvas
watercolor and collage
oil on formica
oil on plexiglass
casein on butcher paper mounted on board
pencil and watercolor
ink on rice paper
acrylic and charcoal on sized canvas
acrylic on sized canvas
acrylic and charcoal on cardboard
acrylic on paper
oil on wood pane
gouache on cardboard
casein on figured fabric gessoed to board
gouache and charcoal on paper
oil on canvas board
gouahe on  paper
tempera on masonite
encaustic on newspaper and cloth over canvas, surmounted by four tinted plaster faces in wood box with hinged front
oil, pencil, metal, photograph, fabric, wood on canvas, plus buttons, mirror, stuffed eagle, pillow tied with cord, and paint tube
oil, acrylic and silkscreen on enamel on canvas, two panels
acrylic and fabric on canvas
acrylic and oil paintstick on canvas, three panels
oil on canvas, mounted on fiberboard
photomechanical reproduction, synthetic polymer and pencil on paper
egg tempera on board
synthetic polymer on composition board
watercolor and collage on paper
egg tempera on canvas
felt banner
magna on primed canvas
tissue paper and magna on upsom board
acrylic
acrylic resin paint on canvas
synthetic polymer paint on canvas
acrylic and plaster on wood
polymer on canvas
watercolor on tissue paper
oil on wood fiberboard
cloth and mixed media
graphite and black crayon on paper
graphite and colored pencil on paper
oil on fabric
oil on burnt wood panel
gouache and charcoal
graphite, black crayon and colored pencil on paper
collage on stainless steel
oil, gouache, and plaster on canvas
brush, pen, black ink, and crayon on paper
pastel, gouache and ink on paper
oil on gesso board
oil on canvas mounted on fiberboard
enamel on porcelain
oil and mixed media on canvas
oil and sand on canvas
gouache and ink on board
oil, enamel and aluminum paint on canvas
oil and enamel on metal
oil on canvas with nails, tacks, buttons, key, coins, cigarettes, matches, etc.
oil and enamel on paper on masonite
oil and enamel on masonite
oil and pencil on canvas
oil and mixed media on glass
oil, enamel, wooden hobbyhorse head and cotton on canvas on board
watercolor and ink howell paper
oil and enamel paint on canvas
enamel
ink and gouache on mulberry paper
black and colored inks on mulberry paper
black and colored inks and drops of white oil paint on mulberry paper
oil, enamel and aluminum paint
ink on mulberry paper
black and colored ink on mulberry paper
oil on canvas on panel
oil  and enamel on canvas
enamel, aluminum and glass on canvas
oil on canvas mounted on board
watercolor and pencil
watercolor and pastel
oil, enamel, water-based paint and newspaper on paperboard on wood
oil, printed paper and pencil on canvas
oil and paper on canvas
combine painting
fabric, tissue paper and glue on paperboard
engravings, printed paper: fabric, pencil, foil and glue on paper
oil on newspaper on canvas
oil, fabric and newspaper on canvas and wood
gold leaf on fabric on masonite
gold leaf, fabric, newspaper, wood, paper and glue on canvas
gold leaf and fabric on masonite
oil, fabric and newspaper on canvas with wood
dirt and mold on wood box
oil, fabric and newspaper on canvas
oil, fabric, paper and newsprint on two separately stretched canvases
engraving, pencil and glue on paperboard
oil, fabric, newspaper and wood on canvas
oil, pencil, newspaper, rubber balloon, string in plastic box on wood
oil, fabric, newspaper and crayons on canvas and paperboard
engraving, pencil and glue on paper on paperboard
oil on cut cardboard
oil and plastic on canvas and wood
oil and aluminum on canvas
gouache and mixed media
oil, pencil and charcoal on fiberboard
oil, pencil, colored pencil and mixed media on canvas
oil and tempera on canvas
oil and mixed media
tempera and collage on paper
tempera on wood
oil on parchment
oil on canvas with aluminum mular
gouache on board
tempera on board
tempera on composition board
paper, felt, canvas, pressboard, homosote, masonite, kachina board, and plywood on wood
lipsko i: paint, paper, felt, canvas on kachina board
lipsko iii: paint, paper, felt, canvas on tri-wall card board
lacquer, oil, ground glass on etched honeycomb aluminum
wood, cast aluminum, painted wood
mixed mediums on aluminum
bronze and mixed mediums
aluminum, fiberglass, sheet and scrap metal
oil, urethane enamel, fluorescent alkyd, acrylic, printing on canvas, etched magnesium, aluminum, fiberglass
oil, erethane, enamel, fluorescent alkyd, acrylic, printing on canvas, etched magnesium
pencil on cardboard
acrylic and pastel on canvas
gouache and tempera
egg tempera on gesso panel
colored pencil on cardboard
post paint on cardboard
post paint and pencil on cardboard
colored pencil and post paint on cardboard
pencil and post paint on cardboard
oil and graphite on canvas
house paint, crayon and pencil on canvas
oil, pencil and crayon on canvas
oil, crayon and colored pencil on panel
oil, crayon and pencil on canvas
oil and crayon on canvas
distemper and chalk on canvas
house paint and crayon on canvas
collage, oil, crayon, charcoal and pencil on paper
god and silver leaf on paper
acrylic and silkscreen enamel on canvas
acrylic and silkscreen on canvas
silkscreen on linen
acrylic and silkscreen on linen
screen enamel on canvas
silkscreen enamel on canvas
feathers and acrylic on canvas
silkscreen on canvas
acrylic and silkscreen with diamond dust on linen
pastel on newsprint
mixed media and collage on plywood
mixed media and collage on board
acrylic, collage and working tv on board
mexed media
mixed media, collage and assemblage (including working mechanical motor) on board
oil, acrylic and collage on canvas, enameled radiator and assemblage (including street noise) on canvas and board
acrylic and collage on board
oil and synthetic on shaped canvas
polymer on board
acrylic, collage and assemblage (including working radio) on board
polymer and enamel on board
mixed media, collage and assemblage (including working clock and radio) on board
tempera on gesso
termpera on masonite
tempera on gesso panel
```

**Comment by terrellt** [comment] 2015-07-06 17:48
`proces`

```
oil painting
Platinum print
Engraving
Stereograph
Oil sketch
Albumen print
Glass possitive
Photographic print
drawn
Radiograph
Etching
Reverse etched and frosted
glassworking; assemblage
collage
painted on carved, interlocking wood panels
albumen print
trompe l'oeil
Serigraph
woodcut
Drypoint, soft-ground etching, and aquatint on  paper
36 x 40 in.
oil on canvas
gelatin-silver print
dry brush
```

**Comment by terrellt** [comment] 2015-07-06 17:49
@jsimic Are you guys using URIs for cultural context? Which controlled vocab?

**Comment by wickr** [comment] 2015-07-06 17:54
@terrellt I think this is the higher level Painting term: http://www.getty.edu/vow/AATFullDisplay?find=painting&logic=AND&note=&page=1&subjectid=300033618

**Comment by terrellt** [comment] 2015-07-06 18:05
@wickr++

**Comment by terrellt** [comment] 2015-07-06 18:06
The rights statement associated with this is "Copyright resides with the creator(s) of the image or their assigns and may be subject to copyright restrictions.; The use of this image is intended solely for educational purposes and for individuals affiliated with Oregon State University."

Do we know how that maps? @wickr @boockmi?

**Comment by terrellt** [comment] 2015-07-06 18:24
Photography: http://vocab.getty.edu/aat/300046300
Drawing: http://vocab.getty.edu/aat/300033973
Print: http://vocab.getty.edu/aat/300041273
Diagram: http://vocab.getty.edu/aat/300015387
Sculpture: http://vocab.getty.edu/aat/300047090
Architecture: http://vocab.getty.edu/aat/300263552 (unsure about this one)
Documentary Photography: http://vocab.getty.edu/aat/300134547
Glasswork: http://vocab.getty.edu/aat/300010898
painting: http://vocab.getty.edu/aat/300033618
Multimedia works: http://vocab.getty.edu/aat/300047910
Assemblages (sculpture): http://vocab.getty.edu/aat/300047194
Collage: http://vocab.getty.edu/aat/300033963
Photomontage: http://vocab.getty.edu/aat/300134699
Screen print: http://vocab.getty.edu/aat/300178688
Installation: http://vocab.getty.edu/aat/300182935 (unsure)
Stage Design: Um? 
Combine painting: I don't think this exists. http://dbpedia.org/resource/Combine_painting ?

**Comment by jsimic** [comment] 2015-07-06 18:27
@terrellt : Some of those catego are in AAT and we put some of the really general stuff in op_ns. Don't try to control materi, it's not possible. I wouldn't try with proces wither. We're using AAT and op_ns for culture.

**Comment by jsimic** [comment] 2015-07-06 18:32
Stage design = Scenography = http://vocab.getty.edu/aat/300054190

**Comment by terrellt** [comment] 2015-07-06 18:35
@jsimic The cultural contexts I need to map are
American
Flemish
Canadian
Swiss
French
German
Greek (ancient)
English
Chilean
Italian

Do you have the URIs?

**Comment by boockm** [comment] 2015-07-06 18:38
@jsimic Any suggestions as far as rights statement mappings, Julia? What are you going to do with your art slides collections?

**Comment by terrellt** [comment] 2015-07-06 18:41
The above reads like like RR-F and RightsHolder of OSU.

**Comment by boockm** [comment] 2015-07-06 18:44
Right.

**Comment by terrellt** [comment] 2015-07-06 18:44
@boockm That would mean OSU students can download full res tiffs of the art collection, is that correct?

**Comment by boockm** [comment] 2015-07-06 18:46
Well, then, no.

**Comment by boockm** [comment] 2015-07-06 18:48
I don't think so.

**Comment by jsimic** [comment] 2015-07-06 19:00
@terrellt 
American http://vocab.getty.edu/aat/300107956
Flemish http://vocab.getty.edu/aat/300111184
Canadian http://vocab.getty.edu/aat/300107962
Swiss http://vocab.getty.edu/aat/300111221
French http://vocab.getty.edu/aat/300111188
German http://vocab.getty.edu/aat/300111192
Greek (ancient) http://vocab.getty.edu/aat/300020072
English http://vocab.getty.edu/aat/300111178
Chilean http://vocab.getty.edu/aat/300107968
Italian http://vocab.getty.edu/aat/300111198

**Comment by jsimic** [comment] 2015-07-06 19:01
@boockm rr-r for everything copyrighted

**Comment by boockm** [comment] 2015-07-06 19:02
TIFF download ok?

**Comment by terrellt** [comment] 2015-07-06 19:03
@jsimic My hero. Thank you.

**Comment by terrellt** [comment] 2015-07-06 19:40
Example Record:
```ntriples
<http://example.org/ns/1> <http://purl.org/dc/terms/title> "Self-Portrait with Sketchbook" .
<http://example.org/ns/1> <http://purl.org/dc/elements/1.1/creator> "Trumbull, John (American, 1756-1843)" .
<http://example.org/ns/1> <http://purl.org/dc/terms/date> "1801" .
<http://example.org/ns/1> <http://purl.org/dc/terms/temporal> "18th century" .
<http://example.org/ns/1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vocab.getty.edu/aat/300033618> .
<http://example.org/ns/1> <http://opaquenamespace.org/ns/material> "oil on canvas" .
<http://example.org/ns/1> <http://opaquenamespace.org/ns/material> "oil painting" .
<http://example.org/ns/1> <http://opaquenamespace.org/ns/culturalContext> <http://vocab.getty.edu/aat/300107956> .
<http://example.org/ns/1> <http://id.loc.gov/vocabulary/relators/rps> "Yale University Art Gallery, New Haven, Connecticut, United States" .
<http://example.org/ns/1> <http://purl.org/dc/terms/identifier> "1264.11" .
<http://example.org/ns/1> <http://purl.org/dc/terms/rights> <http://www.europeana.eu/rights/rr-f/> .
<http://example.org/ns/1> <http://purl.org/dc/elements/1.1/rights> "Copyright resides with the creator(s) of the image or their assigns and may be subject to copyright restrictions. The use of this image is intended solely for educational purposes and for individuals affiliated with Oregon State University." .
<http://example.org/ns/1> <http://opaquenamespace.org/ns/full> "Volume1\\107.tif" .
<http://example.org/ns/1> <http://purl.org/dc/terms/replaces> <http://oregondigital.org/u?/art,1> .
<http://example.org/ns/1> <http://opaquenamespace.org/ns/set> <http://oregondigital.org/resource/oregondigital:art> .
<http://example.org/ns/1> <http://opaquenamespace.org/ns/contributingInstitution> <http://dbpedia.org/resource/Oregon_State_University> .
```

**Comment by terrellt** [comment] 2015-07-06 19:44
A lot of these creators are in the LC Name Authority. Do we want to try?

**Comment by terrellt** [comment] 2015-07-06 23:39
I tried - I got about 71% of them, missing 157. Log here: https://gist.github.com/terrellt/af78d0aa7b0241bfd756

I'm tempted to stop there, unless someone wants to map 157 names to URIs.

**Comment by terrellt** [comment] 2015-07-06 23:40
Example Record Round 2:
```
<http://example.org/ns/27> <http://purl.org/dc/terms/title> "Upper Cascades, Columbia River" .
<http://example.org/ns/27> <http://purl.org/dc/terms/creator> <http://id.loc.gov/authorities/names/nr98035620> .
<http://example.org/ns/27> <http://purl.org/dc/terms/date> "1857" .
<http://example.org/ns/27> <http://purl.org/dc/terms/temporal> "19th century" .
<http://example.org/ns/27> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vocab.getty.edu/aat/300033618> .
<http://example.org/ns/27> <http://opaquenamespace.org/ns/material> "watercolor" .
<http://example.org/ns/27> <http://opaquenamespace.org/ns/measurements> "9 1/2 x 12 in." .
<http://example.org/ns/27> <http://opaquenamespace.org/ns/culturalContext> <http://vocab.getty.edu/aat/300107956> .
<http://example.org/ns/27> <http://id.loc.gov/vocabulary/relators/rps> "Private Collection" .
<http://example.org/ns/27> <http://purl.org/dc/terms/identifier> "463" .
<http://example.org/ns/27> <http://purl.org/dc/terms/rights> <http://www.europeana.eu/rights/rr-f/> .
<http://example.org/ns/27> <http://purl.org/dc/elements/1.1/rights> "Copyright resides with the creator(s) of the image or their assigns and may be subject to copyright restrictions. The use of this image is intended solely for educational purposes and for individuals affiliated with Oregon State University." .
<http://example.org/ns/27> <http://opaquenamespace.org/ns/full> "Volume1\\209.tif" .
<http://example.org/ns/27> <http://purl.org/dc/terms/replaces> <http://oregondigital.org/u?/art,27> .
<http://example.org/ns/27> <http://opaquenamespace.org/ns/set> <http://oregondigital.org/resource/oregondigital:art> .
<http://example.org/ns/27> <http://opaquenamespace.org/ns/contributingInstitution> <http://dbpedia.org/resource/Oregon_State_University> .
```

**Comment by terrellt** [comment] 2015-07-07 15:39
@jsimic @sseymore @boockm @wickr Can you take a look at the example record and give me the go ahead or not?

**Comment by jsimic** [comment] 2015-07-07 16:03
Not using URIs for rps?

**Comment by terrellt** [comment] 2015-07-07 16:07
> Not using URIs for rps?

I guess I assumed it wasn't possible. Are all yours in OpaqueNS?

**Comment by jsimic** [comment] 2015-07-07 16:08
We use ULAN, LC and op_ns.

**Comment by wickr** [comment] 2015-07-07 18:08
@terrellt It looks like RR-R for the rights on this one? Other than that and the Repositories the Example Record #2 looks good. 

I think someone should map the remaining Creators to URIs, assuming they're very likely to be there. I volunteer to do it if no one else wants to. 150 isn't really that many.

**Comment by terrellt** [comment] 2015-07-08 00:29
https://gist.github.com/terrellt/79fc5bdfd037cc07e398 There's the mapping cache for repositories and creators. I'll try and do a scan-through tomorrow, although I should be sprinting on PCDM stuff.

**Comment by terrellt** [comment] 2015-07-09 23:27
Cleaned up most of the ULAN matches.

**Comment by terrellt** [comment] 2015-07-09 23:27
For creators*

**Comment by terrellt** [comment] 2015-07-09 23:39
@boockm @jsimic Is it really RR-R? #657 says `RR-R means "hide from everyone" except for those in AccessRestrictions; can add UseRestrictions (SCUA at UO)` - which would mean no item record view. Is that correct?

**Comment by kestlund** [comment] 2015-07-10 00:18
@terrellt: yes, those AAD ones should be RR-R. They should be OSU only and item record view based on that IP range, a URI in the Access Restrictions for OSU only and any use restriction note that is often a reproduction of the old dc:rights in CDM. It's akin to our Art & Arch (aa-images), except we let OSU see them, too. @jsimic @boockm , yes?  Not sure where the SCUA at UO note comes from.

**Comment by terrellt** [comment] 2015-07-10 15:23
@kestlund Are we using AccessRestrictions or RightsHolder?

**Comment by terrellt** [comment] 2015-07-10 15:26
Also, what's the AccessRestrictions URI if we're using that?

**Comment by kestlund** [comment] 2015-07-10 15:40
See controlled vocab discussed here:
https://github.com/OregonDigital/oregondigital/issues/657

Note: the new list

UOopen
UOrestricted
OSUopen
OSUrestricted
Allrestricted

@jsimic why did we need the "open" ones, since they aren't restricted?

**Comment by jsimic** [comment] 2015-07-10 15:54
We were trying to think of all possible contingencies. Who knows what the future holds?

**Comment by terrellt** [comment] 2015-07-10 15:54
@jsimic @sseymore What's the predicate for AccessRestriction? http://opaquenamespace.org/ns/AccessRestriction ? And do those UO/OSU predicates exist? Can we just use the dbpedia URIs?

**Comment by terrellt** [comment] 2015-07-10 16:50
I think I've mapped as many repositories and names as I can.

**Comment by terrellt** [comment] 2015-07-10 16:50
Caches here: https://gist.github.com/terrellt/953ca0ecd8d9a3ff31f0

**Comment by terrellt** [comment] 2015-07-10 16:58
Here's an example record:
```
<http://example.org/ns/18> <http://purl.org/dc/terms/title> "Benjamin West" .
<http://example.org/ns/18> <http://purl.org/dc/terms/creator> <http://vocab.getty.edu/ulan/500016005> .
<http://example.org/ns/18> <http://purl.org/dc/terms/date> "1814: head; 1837; background and drapery" .
<http://example.org/ns/18> <http://purl.org/dc/terms/temporal> "19th century" .
<http://example.org/ns/18> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://vocab.getty.edu/aat/300033618> .
<http://example.org/ns/18> <http://opaquenamespace.org/ns/material> "oil on canvas" .
<http://example.org/ns/18> <http://opaquenamespace.org/ns/material> "oil painting" .
<http://example.org/ns/18> <http://opaquenamespace.org/ns/measurements> "30 3/8 x 25 1/4 in." .
<http://example.org/ns/18> <http://opaquenamespace.org/ns/culturalContext> <http://vocab.getty.edu/aat/300107956> .
<http://example.org/ns/18> <http://id.loc.gov/vocabulary/relators/rps> <http://vocab.getty.edu/ulan/500305141> .
<http://example.org/ns/18> <http://purl.org/dc/terms/identifier> "AS3.25" .
<http://example.org/ns/18> <http://purl.org/dc/terms/rights> <http://www.europeana.eu/rights/rr-r/> .
<http://example.org/ns/18> <http://opaquenamespace.org/rights/AccessRestrictions> <http://dbpedia.org/resource/Oregon_State_University> .
<http://example.org/ns/18> <http://purl.org/dc/elements/1.1/rights> "Copyright resides with the creator(s) of the image or their assigns and may be subject to copyright restrictions. The use of this image is intended solely for educational purposes and for individuals affiliated with Oregon State University." .
<http://example.org/ns/18> <http://purl.org/dc/terms/replaces> <http://oregondigital.org/u?/art,18> .
<http://example.org/ns/18> <http://opaquenamespace.org/ns/set> <http://oregondigital.org/resource/oregondigital:art> .
<http://example.org/ns/18> <http://opaquenamespace.org/ns/full> "Volume1\\201.tif" .
<http://example.org/ns/18> <http://opaquenamespace.org/ns/contributingInstitution> <http://dbpedia.org/resource/Oregon_State_University> .
```

**Comment by terrellt** [comment] 2015-07-10 18:25
Currently missing 1,223 tiffs.

**Comment by terrellt** [comment] 2015-07-22 18:39
Ready for review: http://oregondigital.org/reviewer/?f%5Bdesc_metadata__set_label_sim%5D%5B%5D=Art%2C+Architecture+and+Design%24http%3A%2F%2Foregondigital.org%2Fresource%2Foregondigital%3Aart-architecture-design

Who's the review contact for this, @wickr?

**Comment by terrellt** [comment] 2015-07-22 18:39
Sigh, nevermind. Mime type didn't get figured out for a bunch of them.

**Comment by terrellt** [comment] 2015-07-22 19:41
Bulk fixing those items now.

**Comment by terrellt** [comment] 2015-07-22 20:07
All of them are fixed now, it's just processing ~850 derivatives.

**Comment by terrellt** [comment] 2015-07-22 23:15
This is reviewed. @wickr Can we get a set page?

**Comment by wickr** [comment] 2015-07-22 23:17
@terrellt Uh, sure. I don't think it had any pages before though, so I'm not sure what to put on them. Any ideas @tvc15brian  or  @boockm   ?

**Comment by kestlund** [comment] 2015-07-22 23:19
Just confirming @wickr is correct; it did not have pages previously.

**Comment by boockm** [comment] 2015-07-22 23:25
Right, never had one before. @wickr, I'll check in with them to see what they want.

**Comment by terrellt** [comment] 2015-07-23 15:27
If we don't want a decorated set page that's fine. I also forgot to lock these down to OSU, I'll do that after my standups today.

**Comment by boockm** [comment] 2015-07-23 15:36
Cool. I don't think they have anyone around this summer. I emailed them. If they do want images and text on the page we can add it later.

**Comment by terrellt** [comment] 2015-07-23 17:49
Running the restriction to OSU now.

**Comment by terrellt** [comment] 2015-07-23 20:53
All done. Made sure it's only available to OSU. Closing.

**Comment by terrellt** [comment] 2015-07-29 19:05
VRA predicates are broken. Need to bulk fix them.

**Comment by terrellt** [comment] 2015-07-29 19:22
Fixing with
```ruby
def fix_resource(a)
  predicates = [RDF::URI("http://opaquenamespace.org/ns/measurements"), RDF::URI("http://opaquenamespace.org/ns/material"), RDF::URI("http://opaquenamespace.org/ns/culturalContext")]
  predicates.each do |bad_predicate|
    good_predicate = RDF::URI(bad_predicate.to_s.gsub("ns/","ns/vra/"))
    bad_values = a.resource.query([a.resource.rdf_subject, bad_predicate, nil]).objects.to_a
    good_values = a.resource.query([a.resource.rdf_subject, good_predicate, nil]).objects.to_a
    a.resource.set_value(good_predicate, good_values | bad_values)
    a.resource.set_value(bad_predicate, [])
  end
  a.save
end
```

**Comment by terrellt** [comment] 2015-07-29 21:59
Fixed.

**Closed by terrellt** 2015-07-29 21:59 UTC
